-- Transactional Outbox: o evento é gravado na mesma transação da alteração do processo
-- e publicado no Kafka de forma assíncrona pelo OutboxRelay.
-- "sequencia" define a ordem de publicação (criado_em pode empatar entre transações no mesmo milissegundo).
CREATE TABLE outbox_evento (
    sequencia      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id             UUID          NOT NULL,
    agregado_id    UUID          NOT NULL,
    tipo           VARCHAR(30)   NOT NULL,
    payload        TEXT          NOT NULL,
    correlation_id VARCHAR(64),
    criado_em      TIMESTAMP WITH TIME ZONE NOT NULL,
    publicado_em   TIMESTAMP WITH TIME ZONE,
    tentativas     INTEGER       DEFAULT 0 NOT NULL,
    proxima_tentativa_em TIMESTAMP WITH TIME ZONE, -- backoff após falha específica do evento
    ultimo_erro    VARCHAR(1000),
    CONSTRAINT pk_outbox_evento PRIMARY KEY (id)
);

CREATE INDEX ix_outbox_pendentes ON outbox_evento (publicado_em, sequencia);

-- Linha do tempo do processo, alimentada pelo consumidor Kafka.
-- Sem FK para processo: o histórico sobrevive à exclusão (trilha de auditoria).
-- "sequencia" dá a ordem determinística da linha do tempo: timestamps podem empatar no mesmo
-- milissegundo, mas a ordem de consumo é a ordem causal (mensagens do mesmo processo na mesma partição).
CREATE TABLE historico_processo (
    sequencia     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    evento_id     UUID         NOT NULL,
    processo_id   UUID         NOT NULL,
    tipo          VARCHAR(30)  NOT NULL,
    descricao     VARCHAR(300) NOT NULL,
    ocorrido_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    registrado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_historico_processo PRIMARY KEY (evento_id)
);

CREATE INDEX ix_historico_processo_id ON historico_processo (processo_id, sequencia);
