CREATE TABLE outbox_evento (
    sequencia            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id                   UUID                     NOT NULL,
    agregado_id          UUID                     NOT NULL,
    tipo                 VARCHAR(30)              NOT NULL,
    payload              TEXT                     NOT NULL,
    correlation_id       VARCHAR(64),
    criado_em            TIMESTAMP WITH TIME ZONE NOT NULL,
    publicado_em         TIMESTAMP WITH TIME ZONE,
    tentativas           INTEGER DEFAULT 0        NOT NULL,
    proxima_tentativa_em TIMESTAMP WITH TIME ZONE,
    ultimo_erro          VARCHAR(1000),
    CONSTRAINT pk_outbox_evento PRIMARY KEY (id)
);

CREATE INDEX ix_outbox_pendentes ON outbox_evento (publicado_em, sequencia);

COMMENT ON TABLE outbox_evento IS 'Transactional Outbox: eventos de domínio gravados na mesma transação da alteração do processo e publicados depois no Kafka pelo OutboxRelay';

COMMENT ON COLUMN outbox_evento.sequencia IS 'Ordem de inserção gerada pelo banco; define a ordem de publicação (timestamps podem empatar no mesmo milissegundo)';
COMMENT ON COLUMN outbox_evento.id IS 'Identificador do evento de domínio; chave de idempotência do consumidor';
COMMENT ON COLUMN outbox_evento.agregado_id IS 'Identificador do processo que originou o evento; usado como chave da mensagem no Kafka (mesma partição, ordem garantida por processo)';
COMMENT ON COLUMN outbox_evento.tipo IS 'Tipo do evento: CADASTRADO, ATUALIZADO, STATUS_ALTERADO ou EXCLUIDO';
COMMENT ON COLUMN outbox_evento.payload IS 'Evento serializado em JSON, publicado como valor da mensagem';
COMMENT ON COLUMN outbox_evento.correlation_id IS 'Correlation id da requisição que gerou o evento; enviado no header X-Correlation-Id da mensagem';
COMMENT ON COLUMN outbox_evento.criado_em IS 'Instante em que o evento foi gravado (UTC)';
COMMENT ON COLUMN outbox_evento.publicado_em IS 'Instante da confirmação (ack) do Kafka; nulo enquanto o evento está pendente';
COMMENT ON COLUMN outbox_evento.tentativas IS 'Quantidade de tentativas de publicação que falharam';
COMMENT ON COLUMN outbox_evento.proxima_tentativa_em IS 'Instante a partir do qual o evento pode ser reenviado após falha própria (backoff exponencial); nulo quando pode sair no próximo ciclo';
COMMENT ON COLUMN outbox_evento.ultimo_erro IS 'Descrição da última falha de publicação (tipo e mensagem da exceção), para diagnóstico';

CREATE TABLE historico_processo (
    sequencia     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    evento_id     UUID                     NOT NULL,
    processo_id   UUID                     NOT NULL,
    tipo          VARCHAR(30)              NOT NULL,
    descricao     VARCHAR(300)             NOT NULL,
    ocorrido_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    registrado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_historico_processo PRIMARY KEY (evento_id)
);

CREATE INDEX ix_historico_processo_id ON historico_processo (processo_id, sequencia);

COMMENT ON TABLE historico_processo IS 'Linha do tempo dos processos, alimentada pelo consumidor Kafka; sem chave estrangeira para processo, pois o histórico é mantido após a exclusão (auditoria)';

COMMENT ON COLUMN historico_processo.sequencia IS 'Ordem de consumo gerada pelo banco; ordena a linha do tempo de forma determinística (a ordem de consumo é a ordem causal, pois os eventos de um processo ficam na mesma partição)';
COMMENT ON COLUMN historico_processo.evento_id IS 'Identificador do evento de domínio; como chave primária, garante que uma entrega repetida da mesma mensagem gere um único registro (idempotência)';
COMMENT ON COLUMN historico_processo.processo_id IS 'Identificador do processo a que o evento se refere';
COMMENT ON COLUMN historico_processo.tipo IS 'Tipo do evento: CADASTRADO, ATUALIZADO, STATUS_ALTERADO ou EXCLUIDO';
COMMENT ON COLUMN historico_processo.descricao IS 'Descrição legível do que aconteceu, exibida na linha do tempo (ex.: "Status alterado de ATIVO para SUSPENSO")';
COMMENT ON COLUMN historico_processo.ocorrido_em IS 'Instante em que a alteração aconteceu no processo (UTC)';
COMMENT ON COLUMN historico_processo.registrado_em IS 'Instante em que o consumidor registrou o evento (UTC); a diferença para ocorrido_em mostra a latência do fluxo assíncrono';
